import '/imports/startup/client';
import '/imports/startup/both';
import '/imports/api/studentdata';
import '/imports/api/stuff';
import '/imports/api/goods';
import '/imports/ui/layouts';
import '/imports/ui/pages';
import '/imports/ui/stylesheets/style.css';
import '/imports/ui/components/form-controls/';
